name = "blogscale"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
# NODE_VERSION = "22"
# Add ONLY non-secret variables here if needed
# Secrets should be managed in the Cloudflare Dashboard
